# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "changelog.md"]
markdown: kramdown
highlighter: rouge
permalink: pretty
gems:
  - jekyll-timeago

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: DCgov Project Dashboard

# Author/Organization info to be displayed in the templates
author:
  name: OCTO Innovation Program
  url: mailto:open@dc.gov

# When using this template with a project (repository) page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: '/dcgov-dashboard'

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: '/assets/img/we-are-wdc.png'
logoalt: We Are Washington DC

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: dcgov-dashboard
  description:
  url: https://github.com/DCgov/dcgov-dashboard

google_analytics_ua: UA-2638726-1

# Style Variables
brand_color: "#BF0000"

jekyll_timeago:
  depth: 1 # Level of detail
  today: 'today'
  yesterday: 'yesterday'
  tomorrow: 'tomorrow'
  and: 'and'
  suffix: 'ago'
  prefix: ''
  suffix_future: ''
  prefix_future: 'in'
  years: 'years'
  year: 'year'
  months: 'months'
  month: 'month'
  weeks: 'weeks'
  week: 'week'
  days: 'days'
  day: 'day'
